apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crm-charts.labels" . | nindent 4 }}
data:
{{- with .Values.configmap.data }}    
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.secrets }}    
  {{- toYaml . | nindent 4 }}
{{- end }}
