{{ if .Values.deploymentEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crm-charts.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crm-charts.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "crm-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "crm-charts.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "crm-charts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          {{- if .Values.service.enabled }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe.values | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe.values | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.promtail }}
          volumeMounts:
          - name: shared-data
            mountPath: /tmp
        {{- end}}
        {{- if .Values.promtail }}
        - name: promtail-container
          image: 414085xxxx.dkr.ecr.ap-south-1.amazonaws.com/promtail:main
          args:
          - -config.file=/etc/promtail/promtail.yaml
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: promtail-config
            mountPath: /etc/promtail
          - name: shared-data
            mountPath: /tmp
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.promtail }}
      volumes:
      - name: promtail-config
        configMap:
          name: {{ .Release.Name }}-promtail-configmap
      - name: shared-data
        emptyDir: {}
  {{- end }}
{{ end }}
