{{ if .Values.deploymentEnabled }}
{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "crm-charts.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crm-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector: {{- include "crm-charts.selectorLabels" . | nindent 4 }}
{{- end }}
{{ end }}
